[workspace]
members = ["frenderer", "examples/*", "run-wasm"]
exclude = ["target", "content", "examples/engine-fancy", "examples/engine-fancy-game"]
resolver = "2"

[profile.dev.package.'*']
opt-level = 3
[profile.release]
debug=true