[workspace]
members = ["frenderer", "examples/test2d", "examples/engine-simple", "examples/engine-simple-game"]
exclude = ["target", "content"]
resolver = "2"

[profile.dev.package.'*']
opt-level = 3
[profile.release]
debug=true