[package]
name = "engine-game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
engine = {path="../engine"}
winit = "0.28"
rand = "0.8"

[features]
default = []
webgl = ["engine/webgl"]

